/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BaseUltraVerifier__factory } from "./BaseUltraVerifier__factory";
export { UltraVerifier__factory } from "./UltraVerifier__factory";
