/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseUltraVerifier } from "./BaseUltraVerifier";
export type { UltraVerifier } from "./UltraVerifier";
