//SHORT
pub comptime global TEST_INPUT_SHORT = "The quick br";
pub comptime global TEST_BASE64_ENCODED_SHORT = "VGhlIHF1aWNrIGJy";

//LONG
pub comptime global TEST_INPUT_LONG =
    "The quick brown fox jumps over the lazy dog, while 42 ravens perch atop a rusty mailbox.";
pub comptime global TEST_BASE64_ENCODED_LONG = "VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZywgd2hpbGUgNDIgcmF2ZW5zIHBlcmNoIGF0b3AgYSBydXN0eSBtYWlsYm94Lg==";

//LONG LONG
// pub comptime global TEST_INPUT_LONG_LONG =
//     "The quick brown fox jumps over the lazy dog, while 42 ravens perch atop a rusty mailbox.";
// pub comptime global TEST_BASE64_ENCODED_LONG_LONG = "VGhlIHF1aWNrIGJyb3duIGZveCBqdW1wcyBvdmVyIHRoZSBsYXp5IGRvZywgd2hpbGUgNDIgcmF2ZW5zIHBlcmNoIGF0b3AgYSBydXN0eSBtYWlsYm94Lg==";
