[package]
name = "discrete_log_example"
type = "bin"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
noir_bigcurve = { git = "https://github.com/noir-lang/noir_bigcurve", tag = "v0.9.0" }
bignum = { tag = "v0.7.3", git = "https://github.com/noir-lang/noir-bignum" }