name: Run Foundry-Voting Tests

on:
  pull_request:
    paths:
      - 'foundry-voting/**'
  workflow_dispatch:

jobs:
  test:
    defaults:
      run:
        working-directory: foundry-voting

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Nargo
      uses: noir-lang/noirup@v0.1.2
      with:
        toolchain: stable
      
    - name: Install bb
      run: |
        curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/refs/heads/master/barretenberg/bbup/install | bash
        echo "PATH=$PATH:/home/runner/.bb" >> $GITHUB_ENV
      shell: bash

    - name: Use bbup
      run: |
        bbup
      shell: bash

    - name: Install Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install Dependencies
      run: bun install

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Run Circuit Tests
      run: bun run circuits:test

    - name: Execute Circuits
      run: bun run circuits:execute

    - name: Generate UltraPlonk Proof
      run: bun run circuits:ultraplonk:generate-proof

    - name: Generate Verification Key
      run: bun run circuits:ultraplonk:generate-vk

    - name: Generate Circuit Contract
      run: bun run circuits:contract

    - name: Clean UltraPlonk Proof
      run: bun run ultraplonk:clean-proof

    - name: Run Forge Tests
      run: forge test
